### PR TITLE
Fixes issue when getCommentContent returns false

### PR DESCRIPTION
**Pull request by nunomaduro**
Makes sure a comment always haves a string content.

### CODE REVIEW

**Comment by kukulich** [comment]
@nunomaduro Could je please post test case ?

**Comment by nunomaduro** [comment]
Sure, origin: https://github.com/nunomaduro/phpinsights/issues/62.

Unterminated comments:
```php
/*

Route::get('/', function () {
    return view('welcome');
});
```

**Comment by kukulich** [comment]
I don't know if we need to support this...

**Comment by nunomaduro** [comment]
You don't need to support this, maybe we could adapt to this situation as this is not an empty comment.

**Comment by ttrig** [comment]
This will also take care of files ending with e.g. `/* Line comment */` where the last character is not a newline. :+1:

**Comment by nunomaduro** [comment]
And tests are passing, so. 🤗

**Comment by kukulich** [comment]
For me it's invalid code. I don't I should solve this.

**Comment by francislavoie** [comment]
@kukulich if PHP runs it, it's valid code. This tool can end up being used on legacy apps with totally varying degrees of code quality. When trying to use it with a tool like https://github.com/nunomaduro/phpinsights to assess the code quality, this issue makes things break.

**Comment by kukulich** [comment]
It may be valid code but this repository does need to support all valid codes (and already does not). The code is invalid for me.

**Comment by nunomaduro** [comment]
Alright, what can we make to do things better here? Throwing a fatal exception don't seems right to me.

**Comment by francislavoie** [comment]
To clarify: `getCommentContent` declares a return type of `string`. `substr` returns a string, or false on failure. Simply returning the output of `substr` breaks the return type contract when `substr` returns false. This PR corrects that behaviour and prevents an erroneous fatal from occurring due to the type checker. I don't see what's controversial about that.

**Comment by genesiscz** [comment]
> It may be valid code but this repository does need to support all valid codes (and already does not). The code is invalid for me.

How should I even know what's wrong with my old project and where is this document wrong if only think I get is just a fatal error without any explanation.  Since it's kinda valid code for PHP, I guess other checkers won't find this as an issue. How am I supposed to track this?

**Comment by genesiscz** [comment]
Also, this is PERFECTLY valid code:

/**
 something here /**
*/

PHP won't get mad, this package does. Found out by using -v (verbose) for phpcs

**Pull request closed without merging**
