### PR TITLE
Allow phpstan/phpdoc-parser 1.10

### PR DESCRIPTION
**Pull request by derrabus**

### CODE REVIEW

**Comment by kukulich** [comment]
We may already try 1.10: https://github.com/phpstan/phpdoc-parser/releases/tag/1.10.0

**Comment by derrabus** [comment]
Oh wow. Sure. 😅

**Comment by derrabus** [comment]
Looks good. 🙂

**Comment by kukulich** [comment]
Thanks.

**Comment by simPod** [comment]
👍🏾 would be nice to get a release soon. It's blocking upgrades to few other dependencies that require parse v .10

**Pull request merged**
