### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by alexndlm**

### CODE REVIEW

**Comment by kukulich** [comment]
We need to add tests for new `phpstan/phpdoc-parser` features so we know that everything works as expected.

**Comment by alexndlm** [comment]
@kukulich, how do you usually do this?

**Comment by alexndlm** [comment]
How this test may look? Why is green CI not enough?

**Comment by kukulich** [comment]
There are usually problems with `FullyQualifiedClassNameInAnnotationSniff`, `ReferenceUsedNamesOnlySniff` and `UnusedUsesSniff`. New syntax may not be detected and hence reports false positives or does not report bugs.

**Comment by gemal** [comment]
any chance for a merge and a new release here?

**Comment by alexndlm** [comment]
I have lucky deadlines around the end of the year, and I'm afraid I won't be able to find time for a full analysis and tests.

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/releases/tag/8.7.0

**Pull request closed without merging**
