### PR TITLE
EmptyLinesAroundTypeBrances: added tests, change to fixable error

### PR DESCRIPTION
**Pull request by f3l1x**
PR for #49

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I think that the fixer does not work very well in all situations - it will fix when there's a newline missing, but not when there are more lines than expected. Can you fix that? Thanks.

**Comment by f3l1x** [comment]
@ondrejmirtes Thank you for the feedback. I'll try to.

**Comment by f3l1x** [comment]
@ondrejmirtes I'm quite busy these days. If you would like to resolve it, do not hesitate.

**Comment by kukulich** [comment]
@f3l1x Thanks, I've used some of your code in https://github.com/slevomat/coding-standard/pull/79.

**Pull request closed without merging**
