### PR TITLE
Improve and fix AppVeyor setup

### PR DESCRIPTION
**Pull request by Majkl578**
Check commits separately, diff is a lie. 😆 

Mostly following Doctrine DBAL AppVeyor setup: https://github.com/doctrine/dbal/blob/master/.appveyor.yml

### CODE REVIEW

**Comment by Majkl578** [comment]
Note that caching is disabled for PRs, so it's impossible to see real speed with cached PHP in this PR.

Check performance of a cached build here: https://ci.appveyor.com/project/Majkl578/slevomat-coding-standard/build/1.0.12
It's <2m per stage.

**Comment by kukulich** [comment]
Thanks :) I will compare it with https://github.com/Roave/BetterReflection/blob/master/appveyor.yml

**Comment by Majkl578** [comment]
You can see the diff in ff6a95f12a2ce44010f525af9dd8b9e588ba5e1f, second commit is just renaming the file to dot-file. :)

**Comment by kukulich** [comment]
I decided to use configuration from BetterReflection but thanks to push me to fix it :) I also used some changes from your PR :)

**Pull request closed without merging**
