### PR TITLE
Fix UselessParenthesesSniff

### PR DESCRIPTION
**Pull request by enumag**
https://github.com/slevomat/coding-standard/issues/618#issuecomment-471625652

### CODE REVIEW

**Comment by enumag** [comment]
Failing code I just encountered:

```
if ((yield $this->getPromise()) === null) {
```

This gets "fixed" to

```
if (yield $this->getPromise() === null) {
```

which is of course incorrect

**Comment by kukulich** [comment]
@enumag Can you please add this to tests?

**Comment by enumag** [comment]
Done.

**Comment by kukulich** [comment]
@enumag It would be perfect if you can squash it to one commit. Thank you very much :)

**Comment by enumag** [comment]
@kukulich just use GitHub's Squash-Merge button ;-)

**Comment by enumag** [comment]
I did it all via web UI. I don't have it cloned.

**Comment by enumag** [comment]
@kukulich Could you tag a new version please?

**Pull request merged**
