### PR TITLE
Cover short ternaries in UselessTernaryOperatorSniff

### PR DESCRIPTION
**Pull request by thewilkybarkid**
Rather an edge case!

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
AppVeyor failure is unrelated.

**Comment by Majkl578** [comment]
Can you provide some real-world use case for this? I'd be really interested in seeing one.

**Comment by thewilkybarkid** [comment]
Heh, so would I! Just spotted it when adding a (rather unrealistic) test case so our CS (https://github.com/libero/php-coding-standard/pull/50/files#diff-abd230f3b7a1a6e0e56045b82f054108R9). Reasonably quick and should be harmless to add though.

**Comment by kukulich** [comment]
@thewilkybarkid Please squash commits to one commit and name it in the same way as commits in master.Thank you.

**Comment by kukulich** [comment]
Thanks.

**Pull request merged**
