### PR TITLE
fix(RequireExplicitAssertion): do not throw away `static` type

### PR DESCRIPTION
**Pull request by simPod**
I think this is a bug?

### CODE REVIEW

**Comment by kukulich** [comment]
@simPod The fix looks promising. If you can prepare mergable PR, I can release bugfix version today.

**Comment by simPod** [comment]
@kukulich done. BTW you do not need to release a patch for me, I can wait with this one.

**Comment by kukulich** [comment]
@simPod I'm going to vacation tomorrow so better to do it today :) And I like your PRs to Doctrine CS - more users (and testers) :)

**Comment by simPod** [comment]
enjoy ur vacation then 🙃

**Pull request merged**
