### PR TITLE
Implement PHP.OptimizedFunctionsWithoutUnpacking sniff

### LINKED ISSUE #454: Sniff to check that engine-optimized functions do not use argument unpacking
There is [bunch of PHP functions](https://github.com/php/php-src/blob/850b53df0e3aa1a898db000244290fd0b7ecc8b6/Zend/zend_compile.c#L3916-L3975) that are optimized into specialized VM opcode. This [only works when argument unpacking is not used](https://github.com/php/php-src/blob/850b53df0e3aa1a898db000244290fd0b7ecc8b6/Zend/zend_compile.c#L3912-L3914).

Having a sniff which will point out when such function is used with variadics would be nice.

### PR DESCRIPTION
**Pull request by Majkl578**
closes #454

### CODE REVIEW

**Comment by kukulich** [comment]
It looks the version 4.8 would be necessary :)

**Comment by Majkl578** [comment]
Split tests for namespaced and non-namespaced code into different files, seems to also be affected by #446.

**Comment by Majkl578** [comment]
>  Coverage increased (+0.0001%) to 99.981%

:joy:

**Comment by kukulich** [comment]
Perfect, thanks!

**Pull request merged**
