### PR TITLE
Reset $annotations keys before determining the last content end pointer

### PR DESCRIPTION
**Pull request by echernyavskiy**
```php
var_dump($annotations, $annotations[$annotationsCount - 1]->getEndPointer(), $firstContentEndPointer, $lastContentEndPointer);
```

Before:

```php
array(3) {
        [0] =>
      class SlevomatCodingStandard\Helpers\Annotation#319 (5) {
        private $name =>
        string(5) "@link"
        private $startPointer =>
        int(4974)
        private $endPointer =>
        int(4976)
        private $parameters =>
        NULL
        private $content =>
        string(146) "https://github.com/..."
      }
      [2] =>
      class SlevomatCodingStandard\Helpers\Annotation#317 (5) {
        private $name =>
        string(5) "@todo"
        private $startPointer =>
        int(4984)
        private $endPointer =>
        int(4986)
        private $parameters =>
        NULL
        private $content =>
        string(27) "TODO."
      }
      [1] =>
      class SlevomatCodingStandard\Helpers\Annotation#320 (5) {
        private $name =>
        string(5) "@link"
        private $startPointer =>
        int(4994)
        private $endPointer =>
        int(4996)
        private $parameters =>
        NULL
        private $content =>
        string(40) "https://..."
      }
    }
    int(4986)
    int(4969)
    int(4986)
```

After:

```php
    array(3) {
        [0] =>
      class SlevomatCodingStandard\Helpers\Annotation#319 (5) {
        private $name =>
        string(5) "@link"
        private $startPointer =>
        int(4974)
        private $endPointer =>
        int(4976)
        private $parameters =>
        NULL
        private $content =>
        string(146) "https://github.com/..."
      }
      [1] =>
      class SlevomatCodingStandard\Helpers\Annotation#317 (5) {
        private $name =>
        string(5) "@todo"
        private $startPointer =>
        int(4984)
        private $endPointer =>
        int(4986)
        private $parameters =>
        NULL
        private $content =>
        string(27) "TODO."
      }
      [2] =>
      class SlevomatCodingStandard\Helpers\Annotation#320 (5) {
        private $name =>
        string(5) "@link"
        private $startPointer =>
        int(4994)
        private $endPointer =>
        int(4996)
        private $parameters =>
        NULL
        private $content =>
        string(40) "https://..."
      }
    }
    int(4996)
    int(4969)
    int(4996)
```

### CODE REVIEW

**Comment by kukulich** [comment]
I'm sorry I don't get it :(

**Comment by echernyavskiy** [comment]
@kukulich, so without this change https://github.com/slevomat/coding-standard/pull/426/files#diff-5e1268c343b812d52d53a7f43bae05bdL108 will use the wrong annotation to determine the last content end pointer instead of the last one (see before vs. after).

**Comment by kukulich** [comment]
@echernyavskiy Could you prepare test?

**Comment by echernyavskiy** [comment]
Done. Uncomment the change in `DocCommentSpacingSniff.php` to make the new test fail.

**Comment by kukulich** [comment]
Thanks.

**Pull request merged**
