### PR TITLE
UselessParenthesesSniff: Prevent change to affect result

### LINKED ISSUE #650: UselessParenthesesSniff
This sniff introduces the following change, which is affecting the result:
```diff
-                    $error = ($y - $hX) ** 2;
+                    $error = $y - $hX ** 2;
```

### PR DESCRIPTION
**Pull request by d-claassen**
Fixes #650.

The old implementation could affect results if the parentheses existed to do a part of the calculation first. #650 gave an example of this:

> ```diff
> - $error = ($y - $hX) ** 2;
> + $error = $y - $hX ** 2;
> ```

Other issues like this could occur as well.

```diff
  $y = 1;
  $yy = 2;
  $z = 3;
- $x = ($y + $yy) * $z;
+ $x = $y + $yy * $z;
  // With parentheses $x becomes 9, without parentheses it becomes 7
```

To prevent more false positives like these, I've opted to completely stop removing parentheses when there are other operations dealing with the logic inside the parentheses.

### CODE REVIEW

**Comment by binarious** [comment]
What's holding this PR and the release of [5.1.0](https://github.com/slevomat/coding-standard/issues?q=is%3Aopen+is%3Aissue+milestone%3A5.1.0) back? The failing build doesn't seems to be code-related.

**Comment by mmoll** [comment]
A rebase would also re-kick the build (which comes back :green_heart: here locally).

**Comment by binarious** [comment]
@d-claassen Do you have the time to do a rebase? Otherwise I could recreate the PR.

**Comment by d-claassen** [comment]
I’ll give this a rebase on Monday, hopefully that’ll fix the build!

**Comment by binarious** [comment]
Thanks @d-claassen!
@kukulich Can we get this merged and 5.1.0 released?

**Comment by enumag** [comment]
Looks like this needs another rebase.

**Comment by kukulich** [comment]
I'll probably not use this PR because I have to rewrite the sniff completely.

**Comment by binarious** [comment]
@kukulich Can't 5.1.0 be released without #650 then? A lot of bugs have been closed in the milestone.

**Comment by mmoll** [comment]
> I'll probably not use this PR because I have to rewrite the sniff completely.

I don't get why this pure bugfix can't get pulled in for a new release and postpone a rewrite after that.

**Pull request closed without merging**
