### PR TITLE
Do not fix use statement order if there is a multi-part statement

### LINKED ISSUE #1547: AlphabeticallySortedUses drops secondary parts of use statements
The **SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses** sorts `use` statement order. It works fine if each statement is a single separate statement. However I have found a problem when the use statements are defined with multiple parts. PHP allows for multiple use definitions within one statement, and they can also be split over more than one line, such as
```
use B, BpartTwo;
use D, DpartTwo as Dalias, DpartThree;
use C;
use A as AliasA,
    ApartTwoOnNewLine;
```
When the fixer is run on this file, only the first class within each `use` statement is output, and the secondary (and further) parts are dropped and lost from the output. The result using the above example is:
```
use A as AliasA;
use B;
use C;
use D;
```
The secondary parts are all lost completely, and this is a bug.

### PR DESCRIPTION
**Pull request by jonathan1055**
Fixes #1547

### CODE REVIEW

**Comment by jonathan1055** [comment]
Ha ha, that's ironic!
```
FILE: ...dingStandard/Sniffs/Namespaces/AlphabeticallySortedUsesSniff.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 30 | ERROR | [x] Use statements should be sorted alphabetically. The
    |       |     first wrong one is T_COMMA.
    |       |     (SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses.IncorrectlyOrderedUses)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
``

**Comment by jonathan1055** [comment]
Nice code coverage report on https://app.codecov.io/gh/slevomat/coding-standard/pull/1551
I knew we needed a test for this new work anyway, but good to have it spelled out :-)

**Comment by jonathan1055** [comment]
Review comments do not seem to show up in the PR commits via the tab at the top. Here's a direct link https://github.com/slevomat/coding-standard/commit/4b00083c42e87ead7647e19884a9713ba5b071d6#comments

**Comment by kukulich** [comment]
Thanks.

**Comment by klausi** [comment]
Thanks a lot @kukulich for helping us here and the cross-project collaboration on behalf of the Drupal community :)

**Pull request merged**
