### PR TITLE
Add test for EarlyExit does not report useless else

### PR DESCRIPTION
**Pull request by momala454**
For issue https://github.com/slevomat/coding-standard/issues/1496

### CODE REVIEW

**Comment by kukulich** [comment]
@momala454 So you expect it should report the `else` branch with comment?

**Comment by momala454** [comment]
yes

**Comment by kukulich** [comment]
> Removing "//" and keeping return false doesn't change the report, the else is not reported as useless

So please update the test to the relevant version.

**Comment by momala454** [comment]
I updated the test

**Comment by kukulich** [comment]
Thanks, fixed in https://github.com/slevomat/coding-standard/commit/fe768682a188034717b8d0f9411172af5a17417f

**Pull request closed without merging**
