### PR TITLE
Compatibility with PHP CodeSniffer 2.9

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by kukulich** [comment]
PHP CodeSniffer 2.9.0 is unusable.

**Comment by Majkl578** [comment]
Could you link relevant bug report please?

**Comment by kukulich** [comment]
@Majkl578 I didn't report it yet. There's bug with T_NULLABLE token detection so if you use nullable type hints a lot of sniffs don't work, even core sniffs from PHPCS itself.

**Comment by kukulich** [comment]
https://github.com/squizlabs/PHP_CodeSniffer/pull/1442

**Comment by fprochazka** [comment]
@kukulich it's released!

**Pull request closed without merging**
