### PR TITLE
Added InlineDocCommentDeclarationSniff

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by kukulich** [comment]
cc @VasekPurchart

**Comment by VasekPurchart** [comment]
```
 100 | ERROR | [x] Invalid inline doc comment format "@var
     |       |     $annotationDriver
     |       |     \Doctrine\ORM\Mapping\Driver\AnnotationDriver" for
     |       |     variable $annotationDriver.
```

Works great, bud maybe let's add to the message, what is the correct form? So something like `Type should precede the variable name`?

**Comment by kukulich** [comment]
I've just improved the error message.

**Comment by VasekPurchart** [comment]
👍

**Pull request merged**
