### PR TITLE
Added failing (so far) test for unused uses warning on type comments

### PR DESCRIPTION
**Pull request by meridius**
Referencing https://github.com/slevomat/coding-standard/issues/27

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
@meridius What about using `/**` as the beginning of the comment? It's a different token for PHPCS and the defacto standard for docblocks.

**Comment by meridius** [comment]
@ondrejmirtes But then it would be docblock, not type comment and I'd get error about docblocks not being able to be only on one line. 
Since I would not be able to test it untill evening, I don't know what sniff exactly reports this, but I agree with it.

**Comment by ondrejmirtes** [comment]
Documentation annotations like `@var` or `@see` are always in a docblock `/** */`, that's why I scan them only. Please verify that the sniff works in that scenario.

**Comment by meridius** [comment]
Well, not always they don't. Please see the Netbeans' documentation article about this feature.

https://blogs.oracle.com/netbeansphp/entry/defining_a_variable_type_in

**Comment by ondrejmirtes** [comment]
It's a design decision on our side to support only one type of notation. And that's `/**` in order to be consistent with property and method docblocks.

See for example https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md - PSR-5 proposal about phpDocs - it also supports `/**` only.

Using `/**` can benefit you also when you are using Doctrine annotations, which parse `/**` only too.

I'm going to close this issue for now - if this sniff does not see types inside `/**` or if you have other problems, please open a new one. Thanks.

**Pull request closed without merging**
