### PR TITLE
`SlevomatCodingStandard.Commenting.AnnotationName`: New sniff to check incorrect annotation names

### LINKED ISSUE #1556: Check for valid PHPDoc tags in a case sensitive way
Can we have an option or a new rule to check for consistency in PHPDoc tags regarding its casing?

See doctrine/dbal#6015.

### PR DESCRIPTION
**Pull request by kukulich**
Fixes #1556

### CODE REVIEW

**Comment by greg0ire** [comment]
This seems to be working for `@inheritdoc`, but not for `{@inheritdoc}`.

**Comment by kukulich** [comment]
@greg0ire Please try new version.

**Comment by greg0ire** [comment]
Let's trust @phansys on this 👍

**Comment by phansys** [comment]
Don't trust me. Trust [the pipeline](https://github.com/doctrine/dbal/pull/6015/commits/ff66bcb9821762d9f55b5426910f5f4c3543a7b6) :trollface:

**Pull request merged**
