### PR TITLE
replace `squizlabs/php_codesniffer` with `phpcsstandards/php_codesniffer`

### LINKED ISSUE #1640: `squizlabs/PHP_CodeSniffer` is abandoned
See https://github.com/squizlabs/PHP_CodeSniffer/issues/3932

Will this package switch to https://github.com/PHPCSStandards/PHP_CodeSniffer as it is a direct fork?

### PR DESCRIPTION
**Pull request by LordSimal**
Resolves #1640

### CODE REVIEW

**Comment by ravage84** [comment]
How about the references to the abandoned repo?

https://github.com/search?q=repo%3Aslevomat%2Fcoding-standard%20https%3A%2F%2Fgithub.com%2Fsquizlabs%2FPHP_CodeSniffer&type=code

**Comment by LordSimal** [comment]
Links to specific issue or PR's need to be done on the old repo since the same ID doesn't exist in the new fork.

**Comment by kukulich** [comment]
Thanks.

**Comment by jrfnl** [comment]
Thank you for your support and your enthousiasm embrassing the take-over of the PHP_CodeSniffer package.

In contrast to earlier information, arrangements are now being made to allow the package to continue under its original name on Packagist. The commit (in the new repo) to rename the package [has been reverted](https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/135).

I'd recommend reverting the Composer reference changes and keeping the changes which refer to the repo URL on GitHub.

Sorry for the confusion and thank you for understanding. I hope you'll enjoy the 3.8.0 release, which I expect to release this Friday.

**Pull request merged**
