### PR TITLE
Add `SlevomatCodingStandard.Classes.RequireAbstractOrFinal`

### PR DESCRIPTION
**Pull request by roslov**

### CODE REVIEW

**Review by simPod — COMMENTED** [review]
Many people use doctrine orm that use proxies - cannot declare those classes final so they can be proxified. Is there any way we could provide a configuration for that use case?

**Comment by roslov** [comment]
> Many people use doctrine orm that use proxies - cannot declare those classes final so they can be proxified. Is there any way we could provide a configuration for that use case?

I also use Doctrine. For the proxied classes (like entities) we can add an exclusion, for example:

```xml
<rule ref="SlevomatCodingStandard.Classes.RequireAbstractOrFinal">
    <exclude-pattern>src/Entity/*</exclude-pattern>
</rule>
```

**Comment by simPod** [comment]
exclude dir works I guess, thanks for reply 👌🏾

**Comment by roslov** [comment]
@kukulich, any updates on this?

**Comment by kukulich** [comment]
Thanks.

**Pull request merged**
