### PR TITLE
UnusedUseSniff: hotfix for ampersand in phpdoc

### PR DESCRIPTION
**Pull request by CZechBoY**
Hi,
this pr hotfixes intersection ampersand in phpdocs.
I can add test later.

### CODE REVIEW

**Comment by kukulich** [comment]
I agree with @Majkl578

**Comment by CZechBoY** [comment]
ok, but how do you solve it NOW?

**Comment by Majkl578** [comment]
Use `|`, not `&`, it's not supported by IDEs and other tools anyway.

**Comment by ikvasnica** [comment]
@Majkl578 When I use `|` instead of `&`, PHPStan will complain instead.

**Comment by kukulich** [comment]
@ikvasnica It's a problem of PHPStan.

**Comment by ikvasnica** [comment]
@kukulich There is a reason behing it, see: https://medium.com/@ondrejmirtes/union-types-vs-intersection-types-fd44a8eacbb
I think it makes perfect sense to use intersection types in case of creating mocks, for instance.

**Comment by kukulich** [comment]
@ikvasnica Yes, but it is wrong when PHPStan enforces syntax that is not supported by IDEs and other tools. It should be enforced only if you enable special option or eg. via special `@phpstan-var` annotation.

**Pull request closed without merging**
