### PR TITLE
Failing test

### PR DESCRIPTION
**Pull request by tomasfejfar**

### CODE REVIEW

**Comment by kukulich** [comment]
@tomasfejfar https://github.com/slevomat/coding-standard#slevomatcodingstandardnamespacesunuseduses-

You have to enable `searchAnnotations` option. The option is disabled in the modified test.

**Comment by tomasfejfar** [comment]
This is our settings: 

```
<rule ref="SlevomatCodingStandard.Namespaces.UnusedUses">
        <properties>
            <property name="searchAnnotations" value="true"/>
        </properties>
    </rule>
```

Still fails for us though... I'll try to replicate it

**Comment by kukulich** [comment]
@tomasfejfar https://github.com/slevomat/coding-standard/commit/4fd3471fc42eb7c00890c2b7c89b3ba8b8c727d9 🤷‍♂️

**Comment by tomasfejfar** [comment]
Nejspíš to bude tím, že jsem zapomněl updatovat a jen jsem to povolil v phpcs.xml 🤦

**Pull request closed without merging**
