### PR TITLE
Add ruleset validation in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
I hope you benefit from it.
```yaml
          xml_ruleset: "SlevomatCodingStandard/ruleset.xml"
          xml_ruleset2: "build/phpcs.xml"
```
It simply runs the `xmllint` command.

### CODE REVIEW

**Comment by szepeviktor** [comment]
@kukulich The EC file suggests spaces.
https://github.com/slevomat/coding-standard/blob/bdfd6a2e497d682f01a5d6808843316c73173e18/.editorconfig#L7
What should I do?

**Comment by kukulich** [comment]
I’m sorry I don’t ser any benefit

**Comment by szepeviktor** [comment]
It is just checking ruleset against the PHP schema.
I leave it 100% up to you.

**Comment by szepeviktor** [comment]
Would you like me to close this PR and fix mixed indentation of `build/phpcs.xml`?
Maybe moving comment aboves lines.

**Comment by kukulich** [comment]
Thanks but I don't think I need it.

**Pull request closed without merging**
